### ISSUE TITLE
Final Document

### ISSUE THREAD

**Issue by rslruiz** [groupflbycpa1/py3ApolloProject#4]
Prepare final document. See guidelines in Canvas > Files > project.  Name the final document "py3ApolloProject.docx".

**Comment by rslruiz** [comment]
I cannot find your py3ApolloProject.docx, where is it?

**Comment by stanleyngdlsu** [comment]
sorry po. We forgot to attatch it last night. We attached it na po.

**Comment by stanleyngdlsu** [comment]
Hi po, may we upload the video and poster later today? We have both done but we're finalizing some details lang po. Thanks!

**Comment by roldnton** [comment]
Here is the link to our video presentation sir: https://drive.google.com/file/d/1G9mibMpLqFZSiTaldAX8Mq_lEXibJlqN/view
